name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: make
      run: cd original/src; make -f MAKEFILE
    - name: make check
      run: cd original/src; make -f MAKEFILE check
    - name: make distcheck
      run: cd original/src; make -f MAKEFILE distcheck
